import pyxel
import json

class Music:
    # json files are generated by 8bit BGM Generator
    # https://github.com/shiromofufactory/8bit-bgm-generator/tree/master

    TitleMusicPath = 'musics/title.json'
    ResultMusicPath = 'musics/result.json'
    DaytimeMusicPath = 'musics/daytime.json'
    NighttimeMusicPath = 'musics/nighttime.json'
    MountainMusicPath = 'musics/mountain.json'
    MidnightMusicPath = 'musics/midnight.json'

    TitleMusicIndex = 0
    ResultMusicIndex = 1

    DaytimeMusicIndex = 2
    NighttimeMusicIndex = 3
    MountainMusicIndex = 4
    MidnightMusicIndex = 5

    def __init__(self, sound_index):
        self.sound_index = sound_index
        self.channels = [1, 2, 3]
        self.set_music()

    def play(self, index):
        pyxel.playm(index, loop=True)

    def stop(self):
        for ch in self.channels:
            pyxel.stop(ch)

    def _set_music(self, music_path, music_index):
        index = self.sound_index + music_index * 3
        with open(music_path, "rt") as fin:
            music_json = json.loads(fin.read())
            for ch, sound in enumerate(music_json):
                pyxel.sounds[index + ch].set(*sound)
        pyxel.musics[music_index].set([],
                                      [index + 0],
                                      [index + 1],
                                      [index + 2])

    def set_music(self):
        self._set_music(self.TitleMusicPath, self.TitleMusicIndex)
        self._set_music(self.ResultMusicPath, self.ResultMusicIndex)
        
        self._set_music(self.DaytimeMusicPath, self.DaytimeMusicIndex)
        self._set_music(self.NighttimeMusicPath, self.NighttimeMusicIndex)
        self._set_music(self.MountainMusicPath, self.MountainMusicIndex)
        self._set_music(self.MidnightMusicPath, self.MidnightMusicIndex)
